[profile.default]
src = 'contracts'
libs = ['node_modules', 'lib']
test = 'test/forge'
out = 'artifacts_forge'
cache_path = 'cache_forge'

optimizer = true
optimizer_runs = 1000000

[fuzz]
runs = 10000
max_test_rejects = 60000

[profile.intense.fuzz]
verbosity = 3
runs = 100000
max_test_rejects = 600000
